Add tests for two argument open and update docs
jonasbn/perl-critic-policy-inputoutput-prohibithighprecedentlogicaloperatorerrorhandling pull request #6
Opened 2021-04-09 00:23 UTC by Quipyowert2

# Description

Please include a summary of the proposed improvement or addressed issue.

Added tests for two-argument `open || die`, and updated documentation.

Fixes/addresses (If applicable) #3 (issue)

## Type of change

Please delete options that are not relevant.

- [✓] Bug fix (non-breaking change which fixes an issue)
- [✓] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project, please see the [contribution guidelines](https://github.com/jonasbn/perl-date-holidays/blob/master/CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [✓] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
  The tests I added cause "Literal line breaks in a string" warnings with `perlcritic --top t/test.t`
- [✓] I have added tests that prove my fix is effective or that my feature works
- [✓] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

You might think, that this is one crazy checklist, but it is just as much written for the maintainer of the involved software :-)

2021-04-09 05:22 UTC, jonasbn commented
Closes #3

2021-05-22 10:08 UTC, jonasbn requested changes
Thanks for the contribution, I have some cosmetic issues, I want you to address

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 0, "No bug - with parenthesis");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 0, 'No bug - with parenthesis' );
```

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 0, "No bug - with or and parenthesis");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 0, 'No bug - with or and parenthesis' );
```

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 1, "Two-arg open bug");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 1, 'Two-arg open bug' );
```

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 0, "No bug - with parenthesis");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 0, 'No bug - with parenthesis' );
```

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 0, "No bug - with or");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 0, 'No bug - with or' );
```

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 0, "No bug - with or and parenthesis");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 0, 'No bug - with or and parenthesis' );
```

2021-05-22 10:08 UTC, jonasbn commented on t/test.t
> +    is( scalar @violations, 0, "No bug - with or and parenthesis and whitespace");
Please use single-quotes for non-interpolated strings as described in [ProhibitInterpolationOfLiterals](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals)

```suggestion
    is( scalar @violations, 0, 'No bug - with or and parenthesis and whitespace' );
```

2021-05-22 12:17 UTC, jonasbn commented
I am sorry about the long wait, but since not release has never been made this was not really on my radar. I had created a PR for inclusion into Perl::Critic, this PR has however open for  a long time, so I have retracted it and plan to release this as a stand-alone policy, hoping to get your contribution included.

2021-05-24 03:24 UTC, Quipyowert2 commented
I have changed the test names to use single quotes as requested.

2021-05-24 09:47 UTC, jonasbn approved these changes

2021-05-24 09:47 UTC, merged

2021-05-24 09:49 UTC, jonasbn commented
Hi @Quipyowert2 

Thank you for your contribution, I will prepare and upload a release to PAUSE/CPAN shortly.

Take care